name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

jobs:
  update_tag:
    name: Release the new action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update the ${{ env.tag_name }} tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ env.tag_name }}